### ISSUE TITLE
error_handler could respect error_reporting() settings

### ISSUE THREAD

**Issue by lamosty** [johnbillion/query-monitor#116]
Let's say I want to log `E_USER_WARNING` and not `E_USER_NOTICE` in my theme's *function.php* file. I set 
```
error_reporting(E_USER_WARNING & ~E_USER_NOTICE);
```
at the top of it. Only warnings get recorded into WordPress *debug.log* file, as expected. 

However, Query Monitor still logs all [levels of errors](https://github.com/johnbillion/query-monitor/blob/master/collectors/php_errors.php#L81). I think QM could respect error_reporting() settings too. Or are there any disadvantages to such behavior I don't anticipate yet?

**Comment by johnbillion** [comment]
Originally, Query Monitor did respect the `error_reporting()` levels ([the commented out code is still in place](https://github.com/johnbillion/query-monitor/blob/master/collectors/php_errors.php#L51-L52)).

However, I found that meant you couldn't be sure that a plugin or theme on the site wasn't changing the error reporting levels and therefore hiding errors. I found a plugin in the plugin directory once which had `error_reporting(0)` at the top, and removing it revealed a bunch of errors that were being hidden (presumably by a naïve or incompetent developer).

So that's the primary reason why QM shows all errors on the front end. The secondary reason is that PHP notices are there for a reason. You shouldn't ignore them and if they show up then they can indicate subtle problems with your code . A good example is an `undefined variable` notice. This can indicate that a piece of code is trying to set a variable to a value from another variable, but the source variable's name has been mis-typed or it's not been set due to an unexpected condition.

QM makes it quite easy to ignore notices (or deprecated notices) if you want to. I could add a filter to QM which tells it to respect the `error_reporting()` level, but I'd be hesitant to do so.

What do you think?

**Comment by lamosty** [comment]
I'm using PHP's `trigger_error` with different error levels for logging messages and variables. That is the original use case. However, incompetent developers trying to hide their errors didn't come to my mind.

While adding a filter would solve the problem for me, those developers could hook onto it and disable error reporting. So, you are right.
