### ISSUE TITLE
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM

### ISSUE THREAD

**Issue by pavelevap** [johnbillion/query-monitor#118]
Hi, after latest Query Monitor upgrade there was following error during attempt for activation:

`Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in .../public_html/www/wp-content/plugins/query-monitor/output/headers/php_errors.php on line 69`

Plugin does not work correctly now...

I am not sure what is wrong, maybe old PHP version?

**Comment by johnbillion** [comment]
This shouldn't be related to your PHP version because this is valid since PHP 5.0.

There might have been a problem during the update. Can you delete and re-install Query Monitor and see if that helps?

Does the error still occur if you disable all your other plugins?

**Comment by pavelevap** [comment]
I deleted and reinstalled plugin, but this problem is still here.
Query Monitor 2.6.7 worked well, but after upgrade to 2.7.1 it is broken.

I upgraded plugin on one more website and there is similar error:

`Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/www/something/www/wp-content/plugins/query-monitor/output/html/admin.php on line 128`

Both websites are on different server, different service, but both are using PHP 5.2.17.

I tried to deactivate all other plugins and Query Monitor still does not work.
I tried to downgrade back to Query Monitor 2.6.10 and it works fine.

Thank you for your help.

**Comment by ericnicolaas** [comment]
Just adding my voice here. A client of ours faced this error as well. They are on PHP 5.2. 

The issue is that the `::` operator is called on the variable `$collectors`, instead of on the class name. According to [this](http://stackoverflow.com/a/17333414), this is a problem in 5.2 but accepted in 5.3. 

I `$collectors::get( 'admin' )`

Use: 

`QM_Collectors::get( 'admin' )`

I have tested this on our client's site and it fixes the issue. Submitting a PR.
