### ISSUE TITLE
Footer styles marked as broken

### ISSUE THREAD

**Issue by jameskraus** [johnbillion/query-monitor#126]
The plugin seems to mark styles as "broken" if the `<link rel="stylesheet" ...>` is in the footer of the page. Specifically, I'm using the [Newspaper](http://demo.tagdiv.com/newspaper/) theme and it appends the styles at the end of the page.

**Comment by johnbillion** [comment]
Thanks James, I'll take a look in the next few days. If you could isolate the code in question that would be a huge help.

**Comment by jameskraus** [comment]
I just checked how the developer of the theme is outputting the style. He's actually just `echo`ing it in the footer. I suppose your plugin probably doesn't support that.

**Comment by jameskraus** [comment]
So I tried fiddling with `wp_enqueue_style` and I found out why it wasn't working. Here's what's going on:

 - Register a style with `wp_enqueue_style` without a version number
 - Deregister the style with `wp_deregister_style`
 - `echo` the style in the footer with the version number ("xxxx.css?ver=1.2.3")

I solved the problem by just adding the version number to the `wp_enqueue_style` call.

This is definitely an edge-case scenario, but if the original style dependency did not specify any version, then it might be best to match against the css file without the version string into account ("?ver=1.2.3").

**Comment by johnbillion** [comment]
Thanks James. I think the key points from your steps are:

 * Register a style with `wp_enqueue_style`
 * Deregister the style with `wp_deregister_style`

This means the dependency system can't output the style because it's been deregistered before it's output. This is a valid reason for QM to highlight the style as being broken. Manually `echo`ing the style will have no effect on the dependency system.

Do you think this is the core reason, or is there something else involved?
