### ISSUE TITLE
Remove font-family "Courier New" fallback

### ISSUE THREAD

**Issue by lkraav** [johnbillion/query-monitor#148]
"Courier New" is practically unreadable. Why not just stay with plain `monospace` to avoid handpicking some "special" fonts and let the OS/browser take care of things. Back to topic, anything is better than Courier New though and this is what my Linux laptop undesirably falls back to before `monospace`. See the difference.

Courier New:
![screenshot from 2015-11-04 12-26-20](https://cloud.githubusercontent.com/assets/147228/10935591/ba543f76-82ef-11e5-8199-66b5f10ca7cc.png)

monospace (Deja Vu Sans Mono):
![screenshot from 2015-11-04 12-29-32](https://cloud.githubusercontent.com/assets/147228/10935603/d0a3533e-82ef-11e5-9d02-d7d12ac89ec5.png)

**Comment by johnbillion** [comment]
I introduced that because on Windows machines `monospace` falls back to Courier which looks like something from the 70s.

This is the first report I've had about problems with the fonts on Linux. What browser are you using? It looks like the borders between the table cells are missing, too.

I've handpicked the fonts because I'm allowed to be subjective :)

I think I'll add Deja Vu Sans Mono into the stack before Courier New.

**Comment by lkraav** [comment]
It's Firefox 41.0.2. Borders are invisible because of `.qm td, .qm th { #FFF none repeat scroll 0% 0% !important }` in combination with `border-collapse: collapse` turns everything white.

For font list, I'd of course be grateful if Deja Vu appeared before Courier New, but for example Gnome 3 default is Cantarell. Other desktops have their own choices for their unique look. Seems like a foreverjob to keep up.
