### ISSUE TITLE
Implement Object Cache panel

### ISSUE THREAD

**Issue by lkraav** [johnbillion/query-monitor#156]
It's one of the things I miss about Debug Bar. Is it feasible to extract that panel from Debug Bar source and either convert it into QM core or make a separate addon out of it?

**Comment by johnbillion** [comment]
Thanks for the suggestion (see also #2).

The reason I decided not to implement an object cache panel is because it's only possible to implement when an external object cache isn't in use. If you add an external object cache such as Memcached or APC to your site, there's no standard API to interact with its stats.

The built-in object cache in WordPress has methods and properties that are used by the Cache panel in Debug Bar, but these methods and properties aren't standardised/available in other cache controllers. IIRC, the Memcached cache controller doesn't have any method at all of accessed hit/miss stats.

That said, there may be some value in showing the cache stats for sites that aren't using an external object cache. I'll keep it on the back-burner for now.

**Comment by lkraav** [comment]
Aha. I've been using `redis` + `pecl-redis` and `plugins/debug-bar` was always able to show good stuff for me. I wasn't aware this may not be the case for `memcached`.

**Comment by johnbillion** [comment]
That's good to know. Which Redis plugin are you using? There are at least two that I know of (see #139).

**Comment by johnbillion** [comment]
I've decided not to implement this at this time, but I have added some object cache overview information to the Overview panel.
