### ISSUE TITLE
Deprecated notice on WordPress trunk

### ISSUE THREAD

**Issue by cklosowski** [johnbillion/query-monitor#158]
When running the WordPress develop version, there is a notice of a deprecated function on every page load:

```
[11-Dec-2015 16:24:41 UTC] PHP Notice:  is_comments_popup is <strong>deprecated</strong> since version 4.5 with no alternative available. in /Users/cklosowski/WordPress/src/wp-includes/functions.php on line 3570
```

**Comment by cklosowski** [comment]
Working on  PR Now

**Comment by cklosowski** [comment]
Never mind, seems it's cleared up in latest on Github

**Comment by cklosowski** [comment]
Ok, I've found it, kept not displaying itself, but it's in the array of conditions for the collector conditionals.

**Comment by johnbillion** [comment]
Yeah Weston beat you to it :) #157

**Comment by robincornett** [comment]
I'm using DesktopServer and because of how they handle debugging, this has been a breaking problem for me, making me choose between running trunk or QM (so I've been using 4.4 so I can keep using QM). Finally decided to see about dealing with it myself. If you add this (or something similar) to your dev environment, you can resolve the notice until the fix is in place:

```
add_filter( 'qm/collect/conditionals', 'rgc_vardump_fix_qm' );
function rgc_vardump_fix_qm( $conds ) {
	$key = array_search( 'is_comments_popup', $conds, true );
	if ( false !== $key ) {
		unset( $conds[ $key ] );
	}
	return $conds;
}```

Thought I would add here in case this has been a showstopper for anyone else.
