### ISSUE TITLE
Ignore the missing language files for en_GB/en_US

### ISSUE THREAD

**Issue by Mte90** [johnbillion/query-monitor#181]
![qm](https://cloud.githubusercontent.com/assets/403283/14523740/8e7e1d34-0235-11e6-8906-847331de177d.png)
This is only an extract of the full list but as I can see the majority of the plugins and theme not contain the language files for en because the plugin are in english by default in the code.
So a suggestion to get a list more compact is hide the missing files for that language.

**Comment by johnbillion** [comment]
In the `develop` branch, the "Not Found" message is no longer highlighted in red for `en_US` because almost no plugins or themes will have a `-en_US.mo` file of course.

I'm not sure about doing the same (or hiding it) for other English variants. The aim is to make it easy to spot which translations are missing, even if they are just variants of English.

**Comment by Mte90** [comment]
Maybe we can add a constant to hide to report for english variants, so the developer in the wp-config can hide that.

**Comment by Mte90** [comment]
The test case, default WordPress use en_US but there in my case i didn't know this so i picked en_US to use WordPress in english.
Maybe a way is disable the alert for all the en_* locales.
