### ISSUE TITLE
Conditionally disable the plugin for certain users?

### ISSUE THREAD

**Issue by mishtershmart** [johnbillion/query-monitor#200]
Howdy,

Just wondering if there is a way I can disable this plugin for certain users or in certain contexts? Ideally, I'd like to be able to disable it for everyone except a particular user, but if I could even parse the request and disable it on certain pages, it would also be helpful, as I've noticed this plugin does cause some memory issues on pages that are doing many DB queries.

Cheers!
Phil

**Comment by johnbillion** [comment]
This might be tricky because when QM's `wp-content/db.php` symlink is in place it means QM initialises before pretty much everything else, including mu-plugins and plugins, and well before WordPress determines the current user. The backtrace storage within `$wpdb` is what causes the memory issues on pages with many DB queries.

I guess what you could do is manually add some conditional logic to `wp-content/db.php`. For example:

```php
if ( '/my-slow-page/' === $_SERVER['REQUEST_URI'] ) {
    return;
}
```

Or something via a cookie:

```php
if ( ! isset( $_COOKIE['use_qm'] ) ) {
    return;
}
```

That's about the best I can offer at the moment. You'll also need to remember to back up your changes in case a future update to QM overwrites that file.

**Comment by mishtershmart** [comment]
Thanks for this @johnbillion. Looking in the `db.php` file reveals the `QM_DISABLED` constant, which appears to do exactly what I need – no hacking of the plugin necessary, as I can drop my logic into the `wp-config.php` file and just set that constant using something like you suggest above. 

Thanks again 👍
