### ISSUE TITLE
Authentication box overlaps previous box

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#208]
![screen shot 2016-07-21 at 2 28 37 pm](https://cloud.githubusercontent.com/assets/4573033/17034203/9efd2404-4f4f-11e6-882e-4131386b3f2e.png)

Adding a top margin of 20px to the authentication box fixes the problem:

![screen shot 2016-07-21 at 2 31 56 pm](https://cloud.githubusercontent.com/assets/4573033/17034271/f3c9b59c-4f4f-11e6-80fc-b7ed07d7aed2.png)

Creating a pull request seemed overkill...?

**Comment by johnbillion** [comment]
Hi Caleb.

The margins on the Authentication panel are no different from the other panels. If you inspect any of the other panels you'll see they also overlap.

Each panel in QM has 40px top padding and -20px negative bottom margin, so that the selected panel isn't partially covered by the admin toolbar when you click an item in QM's menu. It's hacky but it's the only way I could get it to work cross-browser.

**Comment by crstauf** [comment]
Yeah, I noticed, was eager to get the hover effect on that last row of one of QMX's panels. But, I added a footer to that table, so, while you're right it is hacky, I don't mind so much anymore.
