### ISSUE TITLE
What is purpose of `ensure_ajaxurl`?

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#215]
For QM, I can't find a purpose to ensure that `ajaxurl` is being explicitly set. Perhaps there was a reason for it at one point, but it does not seem to exist anymore. Please, explain?

As I mentioned in #176, it is a major pain to remove `ensure_ajaxurl` from `wp_head` hook (for whatever reason), and during my experimenting, I couldn't find a reason. I'm not using Automattic's AMP plugin, pages will not be considered valid with script calls, and this little bugger of a function will not go away.

An explanation for `ensure_ajaxurl`, or a solution to remove it would be greatly appreciated.

**Comment by johnbillion** [comment]
The `ensure_ajaxurl` method is only called if you've got any Debug Bar add-on plugins activated, but not Debug Bar itself (in this situation, [QM takes over the display of the Debug Bar add-ons](https://github.com/johnbillion/query-monitor/wiki/Query-Monitor-Add-on-Plugins)). It's not related to AMP.

[The function in Debug Bar](https://plugins.trac.wordpress.org/browser/debug-bar/tags/0.8.4/debug-bar.php?marks=100-107#L99) is used so that any of its extensions can be assured that the `ajaxurl` variable exists in the global scope.

One Debug Bar add-on that I know of that uses `ajaxurl` is [https://wordpress.org/plugins/debug-bar-console/](Debug Bar Console).

It's a nasty pattern, but I had to stick to it so those add-ons continue to work in QM.

**Comment by crstauf** [comment]
Do you have a list of the Debug Bar add-on plugins? To my knowledge I don't have any of those plugins installed, but `ensure_ajaxurl` is being called.

**Comment by johnbillion** [comment]
I don't have a list handy, although the debug-bar tag on w.org lists some of them.

Can you grep your wp-content directory for ajaxurl to see if any of your plugins are using it?

**Comment by crstauf** [comment]
Confirmed I don't use any of those plugins. When I comment out the `add_action` hook for `ensure_ajaxurl`, the script is removed, so it's definitely being added by QM.

**Comment by crstauf** [comment]
Also, deactivated all plugins (except QM), and output of `ensure_ajaxurl` remains.
