### ISSUE TITLE
Possible bug in SQL validation

### ISSUE THREAD

**Issue by Beee4life** [johnbillion/query-monitor#272]
I run your plugin since a few weeks. Today I ran into [this](https://imgur.com/a/15iGS) database error.

The error came on [this](https://github.com/Beee4life/acf-city-selector/blob/check-before-live/ACF_City_Selector.php#L118) specific function.

I verified the SQL through a few validators, all came back without an error and the function does what it needs to do. Which leads me to believe the validation might not work 100%.

I can be wrong, but I can't find an error on my side.

**Comment by johnbillion** [comment]
Thanks for the message. QM doesn't determine whether or not the SQL contains an error - it simply passes on the error message from MySQL.

The problem is in your usage of `dbDelta()`. You don't need to include the `IF NOT EXISTS` clause. The documentation for this function is terrible, so you're not the only one to make this mistake. Simply remove the `IF NOT EXISTS` clause and `dbDelta()` will correctly handle creating and updating the table as necessary.

**Comment by Beee4life** [comment]
Thanks, that indeed fixed the trick.
