### ISSUE TITLE
tree table rate shipping php error when query monitor is active

### ISSUE THREAD

**Issue by marjoleinsileon** [johnbillion/query-monitor#273]
On my site with woocommerce 3.2.1 and tree table rate shipping plugin enabled the add to cart button is unresponsive when query monitor is enabled. Query monitor detect 2 php errors, see attachment. I contacted the tree table rate shipping plugin author and he asked me to contact you because he believes it is a bug in query monitor. 
He wrote the following reply to me:
"The issue is that error reporting plugins (either Debug Bar or other ones) might ignore the PHP internal error reporting level which might be causing issues with ajax requests used for the Add to Cart button.

That's how it works on the example of the 'section' notice from your screenshot. Tree Table Rate Shipping asks PHP to get 'section' variable. By default, if the value is not set PHP will report this as a "notice". However, the plugin marks its variable request with the so-called error reporting control operator (the '@' symbol), saying, like 'it's ok if there is no value, just ignore it then'. Since it's an absolutely legitimate language feature, PHP doesn't report any error in the case. However, it's possible to override this behavior with custom code like Debug Bar and others do. Their authors, however, sometimes do forget about the error control operator which they must respect due to the language specification.

You might want contact authors of the error reporting plugin you are using about the bug. You can forward them this email to make sure they understand what you are talking about."

![yumbox tapas de bentofabriek](https://user-images.githubusercontent.com/32901122/31718205-40e65be4-b40f-11e7-9cc6-a328db956e9d.png)

**Comment by johnbillion** [comment]
Thanks for the report.

QM logs all errors, including `@`-suppressed errors such as this, but doesn't output the error directly in any Ajax responses. Therefore, QM doesn't break Ajax calls by outputting errors that would otherwise be suppressed when QM is not active.

That said, QM does add such errors to the headers in Ajax responses. It could well be that your site contains so many errors that this causes the header response size to exceed that allowed by your web server.

Your best approach is to use your browser developer tools to inspect the Ajax calls and see what's going on. There could be an erroneous response code from the server (which will also be logged in your server logs) in the Network tab, or there could be a JavaScript error in the Console tab.
