### ISSUE TITLE
Can't close Query Monitor window

### ISSUE THREAD

**Issue by matthisamoto** [johnbillion/query-monitor#326]
When I view my front-end pages, the QM window appears automatically at the bottom and I cannot close it with the X button. Other buttons within the window seem to work fine. While in the admin, the window only appears when I click the toolbar stats, and it closes properly when I click the button. No JavaScript errors are thrown when I try to close it, it just won't close.

**Comment by johnbillion** [comment]
Thanks for the report. This might be the result of QM's fallback behaviour which attempts to make QM usable when jQuery isn't available. I'm going to add in some extra debugging messages.

Can you let me know which theme you're using please?
Is jQuery in use on the front end of your site?
Do you have a plugin installed which might be altering the way that jQuery loads on the front end?

**Comment by johnbillion** [comment]
QM has jQuery as a dependency, yes, but it doesn't include its own version.

Can you try something for me please? Since version 3.0, QM uses `jquery-core` as its dependency but I think I need to switch it back to `jquery`. Can you alter the below line on your own site to use `jquery` and see if that fixes your problem?

https://github.com/johnbillion/query-monitor/blob/7b315a5828bde856d048a0256ed342e03c065353/dispatchers/Html.php#L138-L140

Let me know what you find out.

**Comment by matthisamoto** [comment]
I've updated my theme to just run off of the core jQuery from WordPress, down to only one instance now, and regardless of how deps are set in `Html.php`, `jquery` or `jquery-core`, I still have the same issue.

**Comment by RamiSadi** [comment]
Hi, Is there any progress in this issue, I have the same situation and any logged in user can see the QM bottom panel and it can't be closed, every thing of the panel works normally except for the close button.
 I noticed this is only happens for the user role "vendor", I use a multivendor plugin called "wc marketplace".
Is there any solution yet?
Thanks.

**Comment by alpipego** [comment]
I have this problem as well and I think it's caused by the following:

* You at one point dragged the qm title bar, this sets the `qm-container-height` in localstorage
* Whenever you reload the page, qm gets reset to this height
* If the `qm-show` class exists, the inline height overwrites the removal of the class and thus the panel is still open

**Comment by johnbillion** [comment]
Thanks for the PR, @alpipego! Which browser and operating system are you using please?

**Comment by alpipego** [comment]
checked it on Chrome 66, Firefox 59, Chrome Canary and Safari on OSX 10.12.6

**Comment by dev-masta** [comment]
@alpipego 's PR makes it a bit better - the window on front end doesn't close, instead it's like I dragged it to the bottom (height 0, everything is hidden except the top bar).
On backend everything still works fine.
The "jquery" vs "jquery-core" thing didn't help either.

Using custom theme, loading WordPress jquery (1.12.4), got same behavior in Chrome and Firefox.

**Comment by johnbillion** [comment]
Thanks for the info.

I don't usually ask this but so far I'm unable to reproduce this problem. Does anyone have a publicly accessible site that is exhibiting this behaviour? If so, it would be great if I could get a user account on the site so I can log in and take a look at the problem.

If anyone is willing to do that, my email address is john at johnblackbourn dot com. Cheers!

**Comment by dev-masta** [comment]
Sure, if I could replicate the issue :)
I just tried to do it, and the issue is gone.
Then I thought that the issue might be in the fact that I'm using the local server - it's not.
It's not about the plugins I use.

Just some themes are causing this and I'm still investigating what is the difference between those themes.
(Unfortunately, can't send you the ones that are causing it, yet)

**Comment by johnbillion** [comment]
@dev-masta was kind enough to give me access to his environment after all and I tracked down the problem. QM respects the `no-js` class on the `html` tag (or the `body` tag) and there is no JS in place in the theme on the site to replace this class name with `js`. This causes QM to fall back to a mode whereby it is at least somewhat usable when there's no JavaScript available.

I'm going to remove this particular fallback behaviour because it's really a remnant of the behaviour of QM prior to the new UI being introduced.

**Comment by dev-masta** [comment]
@johnbillion that's the least I could do!
I'm sorry this caused issues for you and others (and I'm sorry I have to work with such poor themes too).
But I'm glad things are moving forward despite all that - thanks for a great plugin once again!

**Comment by alpipego** [comment]
I can confirm that the site where I experienced this issue, also had a `no-js` class on the html element around. 🎉💯

**Comment by zeenahz** [comment]
It is happening with DIVI theme on Chrome.
