### ISSUE TITLE
Resume timer

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#341]
An optional enhancement, as this functionality technically already exists (just create a new timer), but would be helpful for organizational and evaluation purposes.

## Scenario
```php
class Theme_Singleton {
    function include_files() {
        do_action( 'qm/start', 'Include files' );
        ...
        do_action( 'qm/lap', 'Include files', 'Core' );
        ...
        do_action( 'qm/lap', 'Include files', 'Features' );
        do_action( 'qm/stop', 'Include files' ); // or 'qm/pause'
    }
}
...
class Theme_Feature {
    function include_files() {
        do_action( 'qm/start', 'Include files' ); // or 'qm/resume'
        ...
        do_action( 'qm/lap', 'Include files', 'Feature A' );
        do_action( 'qm/stop', 'Include files' );
    }
}
```

## Output
|Tracked Function|Time|Memory|Component|
|:---|:---|:---|:---|
|Include files|0.6|~6kb|Theme|
|- Include files: Core|0.2|~2kb|Theme|
|- Include files: Features|0.3|~3kb|Theme|
|- Include files: Feature A|0.1|~1kb|Theme|

**Comment by johnbillion** [comment]
@crstauf I've also been playing around this afternoon with this and I've decided that it over-complicates the calculations for the timings and the memory use, especially when combined with laps, and, funnily enough, especially when _not_ combined with laps.

I'd be happy to consider the feature if you want to work on a patch, but otherwise it's not something I'm interested in spending any more time looking into.

Cheers!
