### ISSUE TITLE
Too many redirects on WP Dashboard

### ISSUE THREAD

**Issue by melior88** [johnbillion/query-monitor#344]
When enabling the plugin I have a TOO_MANY_REDIRECTS error on http://my-site.com/wp-admin/ but not on http://my-site.com/wp-admin/index.php

It took me a while to figure out it was because of your plugin.

Any clues?

Query Monitor version: 3.0.1
WordPress version 4.9.6

**Comment by johnbillion** [comment]
That sounds very strange. I can't immediately think of anything in QM which would affect redirects.

Can you try clearing all your cookies?

Can you try deactivating your other plugins one by one to see if something clashes?

Cheers!

**Comment by melior88** [comment]
Hey @johnbillion, I already tried disabling every plugin and enabling back one by one. That was in fact, what led me to QM as the culprit of the redirection.
I have tried on different browsers, clearing cookies and cache, or even incognito mode.
Same results every time.

**Comment by johnbillion** [comment]
@melior88 Is this still an issue? If so, can you try switching your theme to one of the default ones such as Twenty Seventeen to see if the problem goes away?

**Comment by melior88** [comment]
Hey @johnbillion already tried that before, didn't work. I haven't checked again on that particular site, let me do it later and I'll let you know.

**Comment by pkarsai** [comment]
I have the same problem. WP version 5.1.1, Query Monitor version. I'm also running Woocommerce. The problem persists regardless of which template I'm using. And I can confirm the same thing as OP did: it happens when trying to load https://www.example.com/wp-admin but it doesn't happen when trying to load https://www.example.com/wp-admin/index.php.
