### ISSUE TITLE
Can You Please Explain How Query Monitor is Tracking Which Query is Triggered By Which Pluging ?

### ISSUE THREAD

**Issue by bv-akash** [johnbillion/query-monitor#357]
I have been watching your code since long now, and didn't  got an insight how you guys are fetching this information. If you can tell it will be helpful

**Comment by johnbillion** [comment]
QM stores the PHP backtrace each time a query runs (it also does this for things like HTTP API calls and PHP errors).

It processes each trace at the end of the page load and looks at the functions that form the trace. It prioritises components in a specific order, for example a trace that includes a function that belongs to a plugin is attributed to the plugin, even if the trace also includes a function that to belongs to the theme. WordPress Core has the lowest priority because otherwise everything would be attributed to Core.

This has proven to be mostly reliable, but not perfect.

Refs:

* https://github.com/johnbillion/query-monitor/blob/dae2820587dea95a169b502cc85b49e5a9195943/classes/Backtrace.php#L119-L165
* https://github.com/johnbillion/query-monitor/blob/dae2820587dea95a169b502cc85b49e5a9195943/classes/Util.php#L70-L184

**Comment by bv-akash** [comment]
Thanks for your reply.

But i had this question, Can we have all the Stats of queries of index page on the Admin Dashboard.
Waiting for reply.
thanks in advance. :)

**Comment by johnbillion** [comment]
At some point I hope something like this will be possible, but it requires QM to support persistent state first, which is something I've been working towards for a long while now. No ETA just yet!
