### ISSUE TITLE
Incompatible with WP Lister

### ISSUE THREAD

**Issue by galapogos01** [johnbillion/query-monitor#382]
Great plugin, really love the detail - especially group by component.

I run the plugin WP Lister to manage eBay listings from WooCommerce products.  When Query Monitor is activated, WP Lister won't ever show an eBay API call such as a listing update as having returned; it sits there indefinitely until it times out.

I have had to deactivate Query Monitor to make my site functional again.

Can provide more info if you tell me how!

**Comment by johnbillion** [comment]
Thanks for the report. This has been raised before: https://wordpress.org/support/topic/conflict-with-query-monitor/

Most likely the cause is that your server hits its memory limit or timeout limit. There's not really anything that QM can do about this. Your best bet is just to disable QM during this process, or increase the memory limit in your server.

**Comment by galapogos01** [comment]
Hi John,

Unfortunately I do not think that is the problem in this case.  I see no out of memory errors in the Apache error log.  

Happy to provide more info if required but it would be nice to leave this open until we at least understand what the cause may be?

Thanks,
Jason

**Comment by galapogos01** [comment]
Nope.
`/var/log$ sudo cat php7.0-fpm.log | grep -i error
[30-Dec-2018 06:37:52] NOTICE: error log file re-opened
`
