### ISSUE TITLE
More friendly solutions when symlink creation fails

### ISSUE THREAD

**Issue by robert777robert777** [johnbillion/query-monitor#390]
Symlink creation fails if symlink creation by php is disabled on the server (a common security approach on shared hosting).
Other plugins simply create a copy of the file instead of symlink.

Proposed solutions:
1. if symlink creation fails but there is no other file at that location create a copy of that file instead of symlink (other plugins do use this approach but currently creating a copy manually isn't accepted by query monitor)
2. display to the user a more friendly error such as "unable to create the symlink because there is another db.php in your system"
or "unable to create symlink, you need to do it manually by running the following command"
and print a readymade command using :
echo ('ln -s ' . get_home_path() . 'wp-content/plugins/query-monitor/wp-content/db.php ' . get_home_path() . 'wp-content/db.php');
On shared hosting with no shell access this command can still be executed by creating a cron job with this command via the hosting control panel (cpanel/etc.)

**Comment by johnbillion** [comment]
Thanks for the report.

In your particular case, what error message does QM show you? It should link out to the wiki page with more info on it. I didn't want to overload the UI with too much info.

**Comment by robert777robert777** [comment]
It shows the link to the wiki.
My suggestion is to show relevant information instead the link to the wiki.
or
Support file copy on systems that don't allow symlink creation

**Comment by johnbillion** [comment]
Thanks!

For now I'm not going to update the help text inside QM itself because it's easier to manage longer pieces of help text on the wiki. I'll add a bit more text explaining that the symlink can also be created via your hosting control panel if necessary.

Regarding the support for copy instead of symlink, this isn't something that I really want to support in QM. The downside of supporting a copy is that it becomes unreliable to keep the `wp-content/db.php` file in sync with changes that I make to the file in the plugin. This is the primary reason a symlink is used - it means whenever the QM plugin gets updated any changes to its `db.php` are immediately in use and the file doesn't need to be re-copied.

Regards
