### ISSUE TITLE
Conflict with Mmenu and Twitter widget

### ISSUE THREAD

**Issue by chrisblakley** [johnbillion/query-monitor#408]
I've been debugging an issue with another library ([Mmenu, and offcanvas menu interface](https://github.com/FrDH/jQuery.mmenu)) where a Twitter feed widget (iframe) was breaking. Mmenu requires that everything within the body tag is wrapped in a single element (like a div) for it to work properly. When that doesn't happen, weird nuances occur like the Twitter feed bug I was running into.

Here are some notes from my troubleshooting:
- https://github.com/FrDH/jQuery.mmenu/issues/969
- https://github.com/chrisblakley/Nebula/issues/1820

What I found was that the `<div id="query-monitor-main">` that Query Monitor adds for the debug interface is being placed outside of my theme's designated body content wrapping div.

Is there any chance that the QM div could be placed at the `wp_footer()` designation? In my theme, `wp_footer()` is placed within my body content wrapper so any footer output from plugins could live there without conflicting.

I know QM has the new debug interface (and the particularly new sidebar option), so I hope this wouldn't interfere with that feature, but currently my sites' Twitter widgets are unfortunately broken for logged-in users and I'm faced with the tough decision of deactivating Query Monitor, Mmenu, or Twitter.

Please let me know if I can provide any additional information.

**Comment by johnbillion** [comment]
Thanks for the message. I'm sorry this breaks your site but QM places its output where it does because it needs to use the `shutdown` hook so it captures queries etc that are performed in the footer of the site.

I'd suggest filing a bug with mmenu if it really does require only one top level element on your page. If that's true then QM is unlikely to be the only thing that will break it :D

**Comment by crstauf** [comment]
@chrisblakley I set `QM_DISABLED` based on my IP address... could you do the same?

**Comment by crstauf** [comment]
@johnbillion Is there a way for QM's output to be moved from `shutdown` to a very high priority on `wp_footer` (say 99999)? Not saying for core, but an adjustment that could be made if the dev wanted to?

**Comment by chrisblakley** [comment]
I could disable it, but I would need to re-enable when I want to debug with it. That being said, I find QM super useful when I'm not explicitly debugging (like when it detects a slow query I wasn't expecting).

**Comment by crstauf** [comment]
I think there's a general recommendation to not run QM in production, so I condition the value of the `QM_DISABLED` constant so that it's only active for my IP address.

You could condition it on that, and/or other things:
- a query parameter
- time of day
- cookie existence
- `file_exists()`

Basically, anything.
