### ISSUE TITLE
[Feature Request] Add panel to rewrite rules.

### ISSUE THREAD

**Issue by kallookoo** [johnbillion/query-monitor#414]
Hi,
First, thanks for this plugin.

Is possible to add the rewrite rules panel on FrontEnd to checking?

**Comment by johnbillion** [comment]
Thanks for the report.

I've decided not to include the full list of rewrite rules in QM's output because there are other plugins that provide this. For example, I recommend [Rewrite Rules Inspector](https://wordpress.org/plugins/rewrite-rules-inspector/).

QM will show you all the _matched_ rewrite rules in the Request panel, which is often useful.
