### ISSUE TITLE
[bug] Notice: Undefined index: counts in /plugins/query-monitor/output/html/assets.php on line 178

### ISSUE THREAD

**Issue by kmvan** [johnbillion/query-monitor#427]
`		$label = sprintf( $type_label['count'], number_format_i18n( $data['counts']['total'] ) );
`

`$data['counts']` maybe empty after plugin updated.

**Comment by johnbillion** [comment]
Thanks for the report.

Did this only occur once on the page load when you updated the QM plugin? If so, yeah that's an annoyance that's caused by the fact that the old version of QM loads at the beginning of the page load, and the new version of QM loads at the end of the page after the plugin has itself been updated. In the past this has even caused a fatal error, but to be honest it's not something that I want to spend any time on.

If that error appears again, do let me know!

**Comment by slaFFik** [comment]
Same issue.
When updating a list of plugins (including Query Monitor to the latest version) on this page - /wp-admin/update-core.php?action=do-plugin-upgrade - I got that notice too (2 of them, identical).
