### ISSUE TITLE
Backupbuddy False Positive Can't find temp file because it is deleted upon completion of backup

### ISSUE THREAD

**Issue by a3rev** [johnbillion/query-monitor#436]
@johnbillion 

Hi John - with the Premium plugin Backupbuddy we are seeing a false positive - Its no big issue just reporting it.

Run a manual backup and Query Monitor reports a suppressed PHP warning

unlink(/home/xxxxxx/public_html/wp-content/uploads/pb_backupbuddy/fileoptions/gzjfam4hk2.txt.lock): No such file or directory

Location: 
1. do_action('toplevel_page_pb_backupbuddy_backup') wp-admin/admin.php:253 
2. pb_backupbuddy_pagescore->__call() wp-includes/class-wp-hook.php:286 
3. pb_backupbuddy_backup->start_backup_process() wp-content/plugins/backupbuddy/controllers/pages/_backup-perform.php:1378 
4. pb_backupbuddy_backup->pre_backup() wp-content/plugins/backupbuddy/classes/backup.php:193 
5. pb_backupbuddy_fileoptions->__construct() wp-content/plugins/backupbuddy/classes/backup.php:332 
6. pb_backupbuddy_fileoptions->load() wp-content/plugins/backupbuddy/classes/fileoptions.php:81 
unlink() 
7. wp-content/plugins/backupbuddy/classes/fileoptions.php:134 
8. wp-content/plugins/backupbuddy/classes/fileoptions.php:134

I look for this file gzjfam4hk2.txt.lock in pb_backupbuddy/fileoptions/ and it is there - but not with the .lock trailing 
gzjfam4hk2.txt

I raised a ticket with the Backupbuddy support and Thomas replied

>Unfortunately I'm not familiar with the Query Monitor plugin and why it's reporting that warning. But it's just a warning and can be ignored if everything is working correctly. The reason the file is not there when you tried to look for it is because those are temp files and are only used temporarily then deleted. And perhaps that's why that Query Monitor plugin is reporting the warning.

>But I've created a ticket for our developers to look into it.

I have linked this to Thomas on their support ticket so maybe he can give you more info if required.

**Comment by crstauf** [comment]
@a3rev What I expect is happening (without having access to BackupBuddy’s code) is they’re calling `unlink()` without checking if the file exists.

QM suppresses errors that occur within function calls that are prefixed with `@`. So instead of checking if the file exists and calling `unlink()`, they just suppress the error with `@unlink()`. I've seen many plugins do this (unfortunately).

**Comment by a3rev** [comment]
@crstauf Thanks - have copied your reply to the open ticket I have on Backbuddy support forum.

Will update you here when get a reply if they don't reply here themselves.

Thanks Caleb

**Comment by crstauf** [comment]
@a3rev I apologize, I don't believe I was clear.

> I've seen many plugins do this (unfortunately).

While I personally am in favor of no errors (suppressed or unsuppressed), using `@unlink()` without checking if the file exists is pretty typical. Because its suppressed, the `E_WARNING` isn't logged to the server's error log, but QM displays it to be thorough.

It is unlikely that BackupBuddy will make a change just to prevent the error from appearing in QM's panel. If you really want to prevent the issue from showing in QM, you could try https://querymonitor.com/blog/2018/07/silencing-errors-from-plugins-and-themes/, but you'll likely find it easier to simply ignore the warning.

**Comment by johnbillion** [comment]
Suppressing PHP errors with the `@` symbol is a bad practice but unfortunately quite common, particularly with file system actions. WordPress core does it a lot.

QM shows you these suppressed errors as crstauf said in order to be thorough and in order to expose errors that you otherwise wouldn't see but could be important. 

It's safe to ignore suppressed errors as long as you've checked to ensure that it's not actually a problem. If you don't have any other PHP errors on the page then QM won't show a red warning in the toolbar.
