### ISSUE TITLE
Authentication cookie not working with Elementor(?)

### ISSUE THREAD

**Issue by mwittmann** [johnbillion/query-monitor#438]
I'm working on a WordPress site that uses Elementor for pages as well as for the site header and footer. When I'm logged in as an admin and Query Monitor is activated, I see the Query Monitor admin bar widget shows up just fine on regular pages as well as in WP admin pages. However, when I set the Query Monitor authentication cookie and log out of WordPress, the Query Monitor admin bar no longer appears on regular pages. The black "admin" bar (with the "Howdy, username" link) does appear... but no Query Monitor access.

I think this is because of the Elementor header---however, I can't verify completely right now because I don't have a separate test environment to switch off the Elementor header. If I log in to WordPress again as a *non-admin* user, on the WP admin pages, the Query Monitor admin bar widget shows up just fine.

Has anyone else seen this issue? Any suggestions for workarounds? I'd really like to be able to use Query Monitor to debug some issues when not logged in to WordPress. Thanks!

**Comment by crstauf** [comment]
First thing that comes to mind: page caching issue. Do you have page caching available and active for your site?

**Comment by johnbillion** [comment]
If the functionality works as expected for non-admin users then yeah the problem could well be caused by edge caching, for example a page cache. The fact that it works for non-admin users rules out the possibility of problems with the cookie path, for example.

I would try temporarily deactivating any page caching plugins to see if that's the problem.
