### ISSUE TITLE
Filter to disable Query Monitor when doing http/curl request with an argument

### ISSUE THREAD

**Issue by wp-seopress** [johnbillion/query-monitor#490]
It would great if we can disable Query Monitor with a filter when use wp_remote_request for example to get the real source code without all the debug information.

**Comment by johnbillion** [comment]
Thanks for the issue.

Can you clarify exactly what you mean please? Does your plugin perform HTTP API requests that you want to hide? If so, that defeats the point of QM and I won't implement that.

Or do you mean that your requesting a WordPress website via the HTTP API and the response also includes output from QM?

**Comment by wp-seopress** [comment]
"Or do you mean that your requesting a WordPress website via the HTTP API and the response also includes output from QM?" 

Yes thats exactly it. To generate an SEO analysis of a page, we request its content via wp_remote_get(). 
If the user has QM, this can generate false positives, hence the need for a filter.

**Comment by johnbillion** [comment]
Thanks.

How does this happen? QM only gets output when the user is authenticated as an admin. Are these requests sending auth cookies?

**Comment by wp-seopress** [comment]
When the user edit/create a post so he's usually an admin / connected to WP.
Yes we send authentification cookies in our request.

**Comment by johnbillion** [comment]
I can see how this is a problem for you, but I think the problem is not limited to QM. For example the same problem exists with other debugging plugins such as Debug Bar and Debug Objects.

You can conditionally define the `QM_DISABLE` constant to disable QM completely (eg. based on a URL query variable) but you'll find that other plugins also output information for logged in users that you might not want.

**Comment by wp-seopress** [comment]
OK thank you for your quick answer.
