### ISSUE TITLE
Out of Memory Errors

### ISSUE THREAD

**Issue by galapogos01** [johnbillion/query-monitor#528]
When I Activate this plugin on my Production site, I get OOM errors. I have raised the per-process memory to 512M and it still runs out.

I think this is due to compatibility with either Mailchimp or Facebook but if you have any steps you would like me to perform to validate I would love to help improve this plugin.

**Comment by johnbillion** [comment]
This is usually caused by a plugin or theme on your site which is performing a very large number of database queries, and when QM tracks them it exhausts the memory.

Unfortunately there's not much that QM can do about this. You should try deactivating your other plugins one by one, and reactivating QM each time, to see if you can find the culprit.

See also the `Related Tools` section of the readme: https://github.com/johnbillion/query-monitor

**Comment by galapogos01** [comment]
John,

Could the plugin be enhanced to stop tracking queries after n limit, to avoid an OOM scenario?

It's not feasible to disable plugins on a production site, and I can't replicate in staging. I would love to go after the plugin author but without data it is obviously difficult.

Would appreciate a little assistance rather than just closing the issue.

**Comment by johnbillion** [comment]
> Could the plugin be enhanced to stop tracking queries after n limit, to avoid an OOM scenario?

Yes it could, and in the long term I do want to do this, but it isn't high on my list of priorities. The irony is that when a request does perform a large number of queries, that's usually the time that you _do_ want to see all the queries in order to debug it. So the issue is not that straight forward. Many years ago QM limited the number of queries shown to 100 but this proved more of a hindrance than a help.

> It's not feasible to disable plugins on a production site, and I can't replicate in staging.

Have you tried exporting your database from production and importing it onto staging?

> Would appreciate a little assistance rather than just closing the issue.

I'm sorry but this is a free plugin and I have limited time to provide support. I understand this is frustrating but this is not a high priority issue.
