### ISSUE TITLE
Warn users if capability is checked without existing

### ISSUE THREAD

**Issue by rmccue** [johnbillion/query-monitor#532]
A problem I've seen appear a few times is code checking custom capabilities (often on CPTs), but where those capabilities don't belong to any roles. This can easily be missed in multisite, as often you'll be using a super-admin user for development, which overrides the proper capability system. You can hence end up with "phantom" capabilities which don't "exist" (i.e. haven't been added to any roles).

We can check for this by collecting every capability checked on the page, collecting every cap from every role, then diffing the two to find out which don't exist. In local testing, this is fast enough to run by default unlike the regular caps panel (~0.001s).

I have a POC plugin for this, can adapt into a QM collector if you think this would be a useful addition. :)

**Comment by johnbillion** [comment]
Yeah happy to have this as a collector, or added to the existing caps collector, as long as it sits behind the same `enabled()` check so it doesn't run unless `QM_ENABLE_CAPS_PANEL` is defined. Some requests can perform absurd numbers of cap checks which is why this is disabled by default.

Question: Should it always be considered something to warn the user about if there are no roles with a cap that was checked on the page? For example, Query Monitor itself supports the `view_query_monitor` capability but this isn't granted to any role by default. I would expect this to be a somewhat common pattern.

**Comment by johnbillion** [comment]
I'm going to close this off because I think it'll too often show a false positive, eg. with the `view_query_monitor` example above.
