### ISSUE TITLE
Error on disabling and deleting Query Monitor

### ISSUE THREAD

**Issue by Wpbeginner** [johnbillion/query-monitor#572]
Hi John,
I came across the recommendation for QM plugin in a you tube video by Ferdy - purpose was to enable amateurs to see page load speed from the dashboard. I am sure it is a wonderful plugin and the purpose I installed it for was to monitor the page load speeds on a new website, my first. Kindly note am not a programmer or a tech person.

I received a mail from HostGator informing that they are deprecating older PHP versions < 7.3 on the server. After that I had problem logging back into my WP dashboard and was able to log back in by changing the plugin folder name.

As all the plugins were automatically disabled, I enabled them one by one. However, unless I enabled QM another plugin (Happy Addons) malfunctioned. I later noticed a drop-in file - db.php Query Monitor Database Class under my plugins tab. On noticing this drop-in file, I enabled QM and all was back to normal.

Please note that I am unable to understand any of the features of QM and would want to delete it. I tried deleting the plugin but the problem persisted with my website slider features. On re-installing and activating it's back to normal.

Kindly let me know as to where I might be going wrong and how can the plugin be deleted w/o affecting the site's functionality.
Regards,
Saurabh K.

![screenshot_20210302_201307](https://user-images.githubusercontent.com/79921649/109665182-ebb74e80-7b93-11eb-9f4e-46fdf382f243.png)
![screenshot_20210302_201351](https://user-images.githubusercontent.com/79921649/109665189-ece87b80-7b93-11eb-8fe3-a20a41b5b07c.png)

**Comment by johnbillion** [comment]
Thanks for the report. The errors that you're seeing are caused by the Happy Elementor Add-ons Pro plugin. It sounds like when your host updated your site to PHP 7.3 they also enabled the display of errors, which should be disabled on a production website.

The reason these error messages disappear with Query Monitor active is it takes over the display of the errors and shows them in the admin toolbar instead.

Best thing to do is:

1. Check if the `WP_DEBUG` or `WP_DEBUG_DISPLAY` constants are set to `true` in your `wp-config.php` file and if so set them to `false`
2. Ask your host for advice, especially if you're on a WordPress specific hosting plan

**Comment by Wpbeginner** [comment]
Many thanks for the prompt response. I will do the needful as suggested and check with Happy Addons Pro team as to why the plugin becomes erratic when QM is disabled/deleted. Does that mean there is nothing specific I need to do/check when I delete QM, as in residual files etc. I simply need to delete QM as already shared, am not technical enough to use its features.

Best thing to do is:

Check if the WP_DEBUG or WP_DEBUG_DISPLAY constants are set to true in your wp-config.php file and if so set them to false _Done._
Ask your host for advice, especially if you're on a WordPress specific hosting plan
_Will check. But they will most probably ask to check with plugin team. Am not on a WP specific plan._

Regards.
