### ISSUE TITLE
list require()-s

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/query-monitor#61]
Are you interested in this feature?

http://us1.php.net/manual/en/function.get-included-files.php

**Comment by johnbillion** [comment]
Related: https://github.com/khromov/wp-query-monitor-included-files

**Comment by szepeviktor** [comment]
Thank you.
The thing is I need *space* to display all those data.
It the latest release *What"s running* displays PHP opcache data.
https://wordpress.org/plugins/whats-running/changelog/

**Comment by khromov** [comment]
Interesting discussion @johnbillion @szepeviktor 

> I don't think that displaying a long list of included files is helpful because it doesn't really tell you much.

I would disagree a little, the point of that list (for me) is to get a quick glance at when plugins include their files. As @szepeviktor said it's generally beneficial to see plugins load files only when they are required. I know the list takes up a lot of space, which is why I added it at a low priority in QM.

I do agree that better overview per-component wuold be nice. I added support for components in version 1.1 of my plugin by using `QM_Util::get_file_component()`.

I'd be open to add grouping by component / filesize by component. PR welcome.  
https://github.com/khromov/wp-query-monitor-included-files

@szepeviktor Regarding merging this into QM, I don't see it as required. That's why there's a nice addons API. I will register my plugin in the official repo soon.

**Comment by szepeviktor** [comment]
> I will register my plugin in the official repo soon.

@khromov Please keep us posted.

**Comment by khromov** [comment]
@johnbillion @szepeviktor Just added group by component in my plugin v 1.3.

Sorting is currently by filesize, but I'll add sortable controls using `QM_Output_Html::build_sorter()` shortly.

Right now both "Included files by component" and "Included files" use the same `QM_Collector` class, will probably 

Here's what it looks like:
![included-by-component](https://cloud.githubusercontent.com/assets/1207507/7577813/026a07e2-f84d-11e4-8625-b0683f51697e.png)

Link:
https://github.com/khromov/wp-query-monitor-included-files

Feedback welcome!

**Comment by szepeviktor** [comment]
Please consider adding opcache memory size as an option. It is implemented in my plugin.

**Comment by khromov** [comment]
@szepeviktor Added OPCache sizes in version 1.3. Not 100% sure about the usefulness. but I did notice that the expansion ratio (opcache_size / file_size) differs quite a bit, from 4-8. Any ideas what causes that?

I did also submit my plugin to the WP repo, but the queue is quite large right now so it'll take a while.

**Comment by szepeviktor** [comment]
When you use opcache it does not matter how big your PHP file is because only the bytecode is cached. So it makes no sense to display file size.

For file sizes the ratio is 512 bytes/pixel, for the opcache memory consuption it is 1024.
https://github.com/szepeviktor/whats-running/blob/master/wp-requires.php#L48-L59

**Comment by szepeviktor** [comment]
Oh! Effectively opcache may consume more memory than the file size.

**Comment by johnbillion** [comment]
I'm going to close this in favour of the above plugin, which is now also listed on the [Query Monitor Add-on Plugins page](https://github.com/johnbillion/query-monitor/wiki/Query-Monitor-Add-on-Plugins).

**Comment by szepeviktor** [comment]
OK
