### ISSUE TITLE
Issue with WP All Import cron

### ISSUE THREAD

**Issue by papazetis** [johnbillion/query-monitor#628]
I am getting a 500 error when cron job for wp all import tries to run.
This happens when "processing" tries to run for the first time after "trigger"

https://www.wpallimport.com/documentation/recurring/cron/

 ```AH01071: Got error 'PHP message: PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vhosts/xxxxxxxxxxxxxx/wp-includes/functions.php on line 6774PHP message: PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /var/www/vhosts/xxxxxxxxxxxx/wp-includes/functions.php on line 5107'```

If I deactivated query monitor, the cron job runs without an issue.

WP Version: 5.8.2
Query Monitor: 3.7.1
WP All Import: 4.7.1

**Comment by johnbillion** [comment]
The short answer is you'll need to deactivate QM during highly intensive operations such as this because it can't log all the queries, actions etc without eating up all your memory.

I'm hoping to get #590 completed soon which will allow plugins to selectively disable QM while performing long running operations.
