### ISSUE TITLE
502 Errors on admin-ajax.php

### ISSUE THREAD

**Issue by mckernanin** [johnbillion/query-monitor#65]
We've been having this issue lately, where admin-ajax 502's out (which won't let you checkout in WooCommerce). We have replicated the issue with only WooCommerce, their Stripe Gateway, and Query Monitor active. Latest versions across the board, disabling query monitor makes the checkout work properly. We host on a Digital Ocean VPS with ServerPilot, which runs nginx as a proxy to apache. 

We get errors like this in the nginx server logs:

```
2014/07/03 11:56:25 [error] 8241#0: *20321 upstream sent too big header while reading response header from upstream, client: %myIP%, server: %siteurl%, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "http://127.0.0.1:81/wp-admin/admin-ajax.php", host: "%siteurl%", referrer: "http://%siteurl%/checkout/"
```

**Comment by neojp** [comment]
Sorry for popping up here, I run into an scenario where the Ajax headers were throwing Haproxy off, a blog post mentions it might be a malformed header rather than memory allocation for buffer proxying. Nginx had the same issue, but got it working by changing the buffer settings.

Looking through the source code, I noticed you can disable the Ajax dispatcher, this should play nice with Haproxy again (and this functionality doesn't hook up into anything just yet, so we should be fine for now).

```
add_filter( 'qm/dispatch/ajax', '__return_false' );
```
