### ISSUE TITLE
Logging/debugging in action and filter hooks not working

### ISSUE THREAD

**Issue by taenzerme** [johnbillion/query-monitor#698]
Hi there,

I'm trying to debug some action that is beeing triggered on saving a custom post type (or posts in general):

`add_action( 'save_post', 'td_debug', 10 );
function td_debug($post_id){
    do_action( 'qm/debug', 'This happened!' );
}`

Nothing happens, no logging.

The code is defined in the themes function.php or a plugin - doesn't matter. No logging.

Logging outside a filter or hook works.

How would I debug the save_post or for example the acf/save_post action?

Best,
Sebastian

**Comment by johnbillion** [comment]
If this is with the block editor, the save is performed in an Ajax request to the REST API and those debugging calls don't get passed back to the main Query Monitor panel from an Ajax request. One day QM will allow this, but it's a while off yet.

If this is with the classic editor then similarly the post gets saved but then you get redirected to another URL, so the debugging call just gets lost due to the redirect.

**Comment by taenzerme** [comment]
Oh my, thanks. Could've thought of this before. Thanks for the quick reply!

So basically it's back to file logging for this.

**Comment by johnbillion** [comment]
Yeah for now, unfortunately. Once #483 is done it'll enable the UI to show data for requests other than the current page load.
