### ISSUE TITLE
[Not an Issue] Retain data by hooks/an option?

### ISSUE THREAD

**Issue by Neoboffin** [johnbillion/query-monitor#903]
Hello!

Is there an option/hook that I can hook into to store timings, slow queries, cache hits/misses, etc? I understand some of this information comes directly from other PHP components but as I already use QM, I figured it's my shortcut.

I'm hoping to re-create something for personal use like Laravel Pulse (https://pulse.laravel.com/), hence the need for this data and for it to be retained.

Thank you in advance,
Sully

**Comment by johnbillion** [comment]
Yes you can extract the collected data from QM for each of its collectors. For example, to get the data for database queries:

```php
$queries = QM_Collectors::get( 'db_queries' );
$data = $queries->get_data();
```

The `$data` value will be an instance of `QM_Data_DB_Queries` so you can see the structure of the data. The "slow" queries are stored in the `expensive` property, duplicate queries in the `dupes` property. You'll have to dig around for the data you need.

To find out the names of all the collectors, take a look at the files in the `collectors` directory which register the collectors, for example [this is the cache collector](https://github.com/johnbillion/query-monitor/blob/9b9a31c77ac05820e2c6d61b46672b731ad43d82/collectors/cache.php#L126).

Off the top of my head I'm not sure what hook you'll need to use to get the complete collected data, it will need to be a very late one, most likely `shutdown` with a priority later than 9 because that's what QM uses to output its data.

Let me know how you get on.

**Comment by johnbillion** [comment]
Probably worth mentioning that I can't guarantee the structure of the data won't change, in fact it will definitely change in Query Monitor 4.0. But if it's for a personal project then you'll just need to check for any changes each time you update QM.

**Comment by Neoboffin** [comment]
Thank you so much @johnbillion!

I'll give `shudown` and `QM_Collectors` a dig into and see what I find. Much appreciated!
