### ISSUE TITLE
Script tags make CSP difficult to implement

### ISSUE THREAD

**Issue by Zealth57** [johnbillion/query-monitor#906]
When implementing a strong CSP that excludes unsafe inline (using things like a nonce or hashes in the CSP) it blocks query monitor output. I'm not 100% sure how many places this affects but there are several places in the code that are `echo '<script type="text/javascript">' . "\n\n";`. If these were converted to using core methods like add_inline_script I believe that has filters / hooks that allow us to control the CSP and add a nonce. Or if there even was a filter on the script tag to add our own attributes that would be helpful. Happy to take a stab at a PR for this if you're open to that.

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by johnbillion** [comment]
I think I need to [switch to using `wp_print_inline_script_tag()` which enables CSP support](https://make.wordpress.org/core/2021/02/23/introducing-script-attributes-related-functions-in-wordpress-5-7/) via the `wp_inline_script_attributes` filter. I am ultimately moving away from Query Monitor using registered and enqueued scripts and styles because I want it to affect as little of the internals of your WordPress site as possible.
